#ifndef XOBJ_H
#define XOBJ_H

#define __FILENAME__ (__builtin_strrchr(__FILE__, '/') ? __builtin_strrchr(__FILE__, '/') + 1 : __FILE__)

#include <iostream>
#include <map>
#include <string>
#include "utilz.h"

class xObject {
protected:
  char buf[1024];
private:
  std::string xid;
  std::string name;
  std::string prompt;
public:
  /*!
   * @brief   Default Constructor for xObject class.
   *
   * @details Initializes an xObject with a unique ID generated by Utilz::get_uuid(), a random name of length 6,
   *          and a prompt set to ">>".
  */
  xObject();

  /*!
   * @brief   Constructor for xObject class with a specified ID.
   *
   * @details This constructor initializes an xObject with a given ID.
   *
   * @param   id The unique identifier for the xObject.
  */
  xObject(std::string);

  /*!
   * @brief   Constructor for xObject class with specified ID and name.
   *
   * @details This constructor initializes an xObject with a given ID and name.
   *          If either the ID or name is empty, it prints an error message and exits the program.
   *          The prompt is set to ">>".
   *
   * @param   id The unique identifier for the xObject.
   * @param   name The name of the xObject.
   * 
   * @note    If the id or name is empty, it prints an error message and exits the program
  */
  xObject(std::string,std::string);

  /*!
   * @brief   Retrieves the name of the xObject.
   *
   * @details This function returns the name of the xObject. The name is a string that represents the identifier of the object.
   *
   * @return  A string representing the name of the xObject.
  */
  std::string get_name();

  /*!
   * @brief   Retrieves the prompt of the xObject.
   *
   * @details This function returns the prompt of the xObject. The prompt is a string that represents the user input prompt.
   *
   * @return  A string representing the prompt of the xObject.
  */
  std::string get_prompt();

  /*!
   * @brief   Retrieves the unique identifier of the xObject.
   *
   * @details This function returns the unique identifier of the xObject. The unique identifier is a string that represents the
   *          internal ID of the object.
   *
   * @return  A string representing the unique identifier of the xObject.
  */
  std::string get_xid();

  /*!
   * @brief   Sets the name of the xObject.
   *
   * @details This function sets the name of the xObject to the given string.
   *          The name is used to identify the object.
   *
   * @param   rename  The new name for the xObject.
   *
   * @return  The size of the new name.
   *
   * @note    The name is not validated in this function. It is the responsibility of the caller to ensure that the name is valid.
  */
  size_t set_name(std::string);

  /*!
   * @brief   Sets the prompt of the xObject.
   *
   * @details This function sets the prompt of the xObject to the given string.
   *          The prompt is used to display a user input prompt.
   *
   * @param   reprompt  The new prompt for the xObject.
   *                     It should be a string that ends with a space character.
   *                     If an empty string is provided, the prompt will be set to ">> ".
   *
   * @return  The size of the new prompt.
   *
   * @note    The prompt is not validated in this function. It is the responsibility of the caller to ensure that the prompt is valid.
   *          If an empty string is provided, the prompt will be set to ">> ".
  */
  size_t set_prompt(std::string);

  /*!
   * @brief   Sets the unique identifier of the xObject.
   *
   * @details This function sets the unique identifier of the xObject to the given string.
   *          The unique identifier is used to uniquely identify the object within the system.
   *
   * @param   id  The new unique identifier for the xObject.
   *              It should be a non-empty string.
   *
   * @return  The new unique identifier of the xObject.
   *
   * @note    The function does not validate the uniqueness of the ID. It is the responsibility of the caller to ensure that the ID is unique.
   *          If an empty string is provided, the internal ID will remain unchanged.
  */
  std::string set_xid(std::string);

  /*!
   * @brief   Default Deconstructor
  */
  ~xObject();
};

#endif // XOBJ_H //
